import 'package:audio_session/audio_session.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:just_audio/just_audio.dart';

/// The kinds of audio cue a timer session can emit.
enum TimerCue { countdown, transition, complete }

/// Bundled asset for each cue. Generated by `scripts/build_timer_cues.py`
/// and recorded in `ASSETS-LICENSE.md`.
const Map<TimerCue, String> timerCueAssets = <TimerCue, String>{
  TimerCue.countdown: 'assets/audio/countdown.wav',
  TimerCue.transition: 'assets/audio/transition.wav',
  TimerCue.complete: 'assets/audio/complete.wav',
};

/// Audio cues for timer boundaries (ADR-4).
///
/// The service is owned at the container level: the cue files are loaded once
/// by [preload] and the same players are reused for the whole session
/// (ADR-4: "never construct a player per beep").
abstract interface class TimerAudioService {
  Future<void> preload();
  Future<void> cue(TimerCue cue);
  Future<void> dispose();
}

/// No-op implementation for web and tests.
class NoopTimerAudioService implements TimerAudioService {
  const NoopTimerAudioService();

  @override
  Future<void> preload() async {}

  @override
  Future<void> cue(TimerCue cue) async {}

  @override
  Future<void> dispose() async {}
}

/// One preloaded clip. A seam over `just_audio`, which needs a platform
/// channel, so the service's behaviour can be tested without one.
abstract interface class TimerCuePlayer {
  /// Loads [assetPath] so the first [play] does not pay the decode cost.
  Future<void> load(String assetPath);

  /// Plays the clip from the start; completes when playback has finished.
  Future<void> play();

  Future<void> dispose();
}

/// [TimerCuePlayer] backed by `just_audio`.
///
/// Session activation is left to [PlatformTimerAudioService], which owns the
/// ducking configuration, so this player must not activate the session
/// itself.
class JustAudioCuePlayer implements TimerCuePlayer {
  AudioPlayer? _player;

  @override
  Future<void> load(String assetPath) async {
    final AudioPlayer player = _player ??= AudioPlayer(
      handleInterruptions: false,
      handleAudioSessionActivation: false,
    );
    await player.setAsset(assetPath);
  }

  @override
  Future<void> play() async {
    final AudioPlayer? player = _player;
    if (player == null) return;
    await player.seek(Duration.zero);
    await player.play();
  }

  @override
  Future<void> dispose() async {
    final AudioPlayer? player = _player;
    _player = null;
    await player?.dispose();
  }
}

/// Platform implementation. Plays the bundled cue files, ducking other audio
/// rather than interrupting it. If a cue cannot be loaded or played it falls
/// back to the system alert sound, and a failure of any kind never reaches
/// the timer.
class PlatformTimerAudioService implements TimerAudioService {
  PlatformTimerAudioService({
    TimerCuePlayer Function()? playerFactory,
    Future<void> Function()? systemAlert,
  })  : _playerFactory = playerFactory ?? JustAudioCuePlayer.new,
        _systemAlert = systemAlert ?? _playSystemAlert;

  final TimerCuePlayer Function() _playerFactory;
  final Future<void> Function() _systemAlert;

  AudioSession? _session;
  AudioSessionConfiguration? _configuration;

  /// Players that loaded successfully, keyed by cue. A cue absent from here
  /// falls back to the system alert.
  final Map<TimerCue, TimerCuePlayer> _players = <TimerCue, TimerCuePlayer>{};
  Future<void>? _preloading;

  @override
  Future<void> preload() => _preloading ??= _preload();

  Future<void> _preload() async {
    await _configureSession();
    for (final MapEntry<TimerCue, String> entry in timerCueAssets.entries) {
      if (_players.containsKey(entry.key)) continue;
      TimerCuePlayer? player;
      try {
        player = _playerFactory();
        await player.load(entry.value);
        _players[entry.key] = player;
      } on Object {
        // Missing plugin (tests, unsupported platform) or an undecodable
        // asset: this cue falls back to the system alert.
        await _disposeQuietly(player);
      }
    }
  }

  Future<void> _configureSession() async {
    try {
      final AudioSession session = await AudioSession.instance;
      final AudioSessionConfiguration configuration =
          const AudioSessionConfiguration.speech().copyWith(
        avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.duckOthers,
        androidAudioFocusGainType:
            AndroidAudioFocusGainType.gainTransientMayDuck,
        androidWillPauseWhenDucked: false,
      );
      await session.configure(configuration);
      _session = session;
      _configuration = configuration;
    } on Object {
      // Audio-session configuration is best-effort on unsupported platforms.
    }
  }

  @override
  Future<void> cue(TimerCue cue) async {
    final AudioSession? session;
    final AudioSessionConfiguration? configuration;
    try {
      await preload();
      session = _session;
      configuration = _configuration;
    } on Object {
      return; // Audio cues must never fail the timer.
    }

    try {
      if (session != null) {
        await session.setActive(
          true,
          fallbackConfiguration:
              configuration ?? const AudioSessionConfiguration.speech(),
        );
      }
      final TimerCuePlayer? player = _players[cue];
      if (player != null) {
        await player.play();
      } else {
        await _systemAlert();
      }
    } on MissingPluginException {
      // A device without audio output is not an error worth surfacing.
    } on Object {
      // Audio cues must never fail the timer.
    } finally {
      try {
        await session?.setActive(false);
      } on Object {
        // Ignore platform-specific deactivation failures.
      }
    }
  }

  @override
  Future<void> dispose() async {
    // A `cue()` racing this sees an empty map and falls back to the alert,
    // and a later `preload()` starts clean, so the service can be reused for
    // the next session.
    final List<TimerCuePlayer> players = _players.values.toList();
    _players.clear();
    _preloading = null;
    for (final TimerCuePlayer player in players) {
      await _disposeQuietly(player);
    }
    try {
      await _session?.setActive(false);
    } on Object {
      // Ignore platform-specific deactivation failures.
    }
    _session = null;
    _configuration = null;
  }

  static Future<void> _disposeQuietly(TimerCuePlayer? player) async {
    try {
      await player?.dispose();
    } on Object {
      // Nothing useful to do if a player will not dispose.
    }
  }

  static Future<void> _playSystemAlert() =>
      SystemSound.play(SystemSoundType.alert);
}

final Provider<TimerAudioService> timerAudioServiceProvider =
    Provider<TimerAudioService>(
  (ref) => kIsWeb ? const NoopTimerAudioService() : PlatformTimerAudioService(),
);
