import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ironyx/core/database/app_database.dart';
import 'package:ironyx/core/database/daos/exercise_dao.dart';
import 'package:ironyx/core/providers.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('seeds every exercise from the bundled asset', () async {
    SharedPreferences.setMockInitialValues(<String, Object>{});
    final prefs = await SharedPreferences.getInstance();
    final database = AppDatabase.forTesting();
    final container = ProviderContainer(
      overrides: [
        appDatabaseProvider.overrideWithValue(database),
        sharedPreferencesProvider.overrideWithValue(prefs),
      ],
    );

    addTearDown(() async {
      container.dispose();
      await database.close();
    });

    await container.read(exerciseSeederProvider.future);
    final exercises = await ExerciseDao(database).watchAll().first;

    // Compared against the asset rather than a hardcoded count. The
    // catalogue is regenerated by scripts/build_exercise_seed.py, so a
    // literal here only ever records how many exercises existed the day
    // the test was written — and fails for the one reason that does not
    // matter. What matters is that the seeder lands *everything* in the
    // file: a partial seed is how the library silently loses exercises.
    final Map<String, dynamic> seed = jsonDecode(
      await rootBundle.loadString('assets/data/exercises_seed.json'),
    ) as Map<String, dynamic>;
    final Set<String> expected = <String>{
      for (final dynamic raw in seed['exercises'] as List<dynamic>)
        (raw as Map<String, dynamic>)['name'] as String,
    };

    expect(expected, isNotEmpty, reason: 'the seed asset itself is empty');
    expect(
      exercises.map((summary) => summary.exercise.name).toSet(),
      equals(expected),
    );
  });
}
