import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ironyx/core/database/app_database.dart';
import 'package:ironyx/core/services/data_export_service.dart';
import 'package:ironyx/core/services/export_schema_upgrades.dart';
import 'package:ironyx/features/settings/domain/export_envelope.dart';

/// Genuine exports written by the app's own code at each historical schema
/// version that ever shipped (5, 7 and 9), generated by checking out those
/// commits and running their `buildJsonExport`. Every table holds a row,
/// and each carries a custom exercise under the pre-v8 convention
/// (`seed_version == 0`) that a workout references.
///
/// They are never regenerated: they stand in for backups users already
/// have. See test/fixtures/exports/README.md.
String _fixture(int schemaVersion) =>
    File('test/fixtures/exports/export_schema_$schemaVersion.json')
        .readAsStringSync();

void main() {
  const DataExportService service = DataExportService();
  late AppDatabase db;
  late Directory snapshotDir;

  setUp(() {
    db = AppDatabase.forTesting();
    snapshotDir = Directory.systemTemp.createTempSync('ironyx_upgrade_test');
  });

  tearDown(() async {
    await db.close();
    snapshotDir.deleteSync(recursive: true);
  });

  Future<List<Map<String, Object?>>> rows(String sql) async =>
      [for (final row in await db.customSelect(sql).get()) row.data];

  for (final int version in <int>[5, 7, 9]) {
    test('an export from schema $version restores into the current schema',
        () async {
      final ImportEnvelope envelope = service.parseImport(_fixture(version));
      expect(envelope.dbSchemaVersion, version);

      await service.applyImport(
        db,
        envelope,
        mode: ImportMode.replace,
        snapshotDirPath: snapshotDir.path,
      );

      expect(
        await rows('SELECT id FROM workouts_table'),
        [
          {'id': 'workouts_1'},
        ],
      );
      expect(
        await rows(
          'SELECT exercise_id FROM workout_exercises_table ORDER BY id',
        ),
        [
          {'exercise_id': 'exercises_1'},
          {'exercise_id': 'ex_custom'},
        ],
      );
      expect(await rows('SELECT id FROM workout_sets_table'), hasLength(1));
      // v7 -> v8: the implicit custom marker becomes the explicit column,
      // exactly as the database migration backfills it.
      expect(
        await rows('SELECT id, is_custom FROM exercises_table ORDER BY id'),
        [
          {'id': 'ex_custom', 'is_custom': 1},
          {'id': 'exercises_1', 'is_custom': 0},
        ],
      );
      // v6 -> v7 added profiles; a schema-5 export simply has none.
      expect(
        await rows('SELECT id FROM profiles_table'),
        hasLength(version >= 7 ? 1 : 0),
      );
    });
  }

  test('upgrading does not modify the parsed envelope it was given', () {
    final ImportEnvelope original = service.parseImport(_fixture(5));
    final ImportEnvelope upgraded =
        upgradeEnvelope(original, toSchemaVersion: db.schemaVersion);

    expect(upgraded.dbSchemaVersion, db.schemaVersion);
    expect(original.dbSchemaVersion, 5);
    expect(original.tables.containsKey('profiles_table'), isFalse);
    expect(
      original.tables['exercises_table']!
          .any((r) => r.containsKey('is_custom')),
      isFalse,
    );
  });

  test('an export already at the current schema passes through unchanged',
      () async {
    final ImportEnvelope envelope =
        service.parseImport(await service.buildJsonExport(db));
    expect(
      identical(
        upgradeEnvelope(envelope, toSchemaVersion: db.schemaVersion),
        envelope,
      ),
      isTrue,
    );
  });

  test('an export from a newer schema is refused, not downgraded', () async {
    final ImportEnvelope newer = service.parseImport(
      _fixture(9).replaceFirst(
        '"dbSchemaVersion": 9',
        '"dbSchemaVersion": ${db.schemaVersion + 1}',
      ),
    );
    expect(newer.dbSchemaVersion, db.schemaVersion + 1);

    await expectLater(
      service.applyImport(
        db,
        newer,
        mode: ImportMode.replace,
        snapshotDirPath: snapshotDir.path,
      ),
      throwsA(
        isA<ImportValidationException>()
            .having((e) => e.message, 'message', contains('newer')),
      ),
    );
  });

  test('an export older than any shipped schema is refused', () async {
    final ImportEnvelope ancient = service.parseImport(
      _fixture(5).replaceFirst(
        '"dbSchemaVersion": 5',
        '"dbSchemaVersion": ${kOldestUpgradableSchemaVersion - 1}',
      ),
    );

    await expectLater(
      service.applyImport(
        db,
        ancient,
        mode: ImportMode.replace,
        snapshotDirPath: snapshotDir.path,
      ),
      throwsA(
        isA<ImportValidationException>()
            .having((e) => e.message, 'message', contains('too old')),
      ),
    );
    expect(await rows('SELECT id FROM workouts_table'), isEmpty);
  });

  test(
      'every schema version from the oldest supported up to the current one '
      'has an export upgrade step', () {
    // The guard for the next schema bump: a migration added to
    // AppDatabase.onUpgrade without a matching step here fails CI instead
    // of silently making every existing backup unrestorable.
    for (int from = kOldestUpgradableSchemaVersion;
        from < db.schemaVersion;
        from++) {
      expect(
        exportSchemaUpgrades.containsKey(from),
        isTrue,
        reason: 'No export upgrade step from schema $from to ${from + 1}. '
            'Add one to exportSchemaUpgrades (a no-op if the migration '
            'changed nothing an export carries).',
      );
    }
    expect(
      exportSchemaUpgrades.keys.every((from) => from < db.schemaVersion),
      isTrue,
      reason: 'A step upgrades past the current schema version.',
    );
  });
}
